### PR TITLE
Resolves issue#2 templates

### PR DESCRIPTION
**Pull request by nekrozofbrionac**
Resolves Issue#2, templates with moderate styling and a deletion functionality

2021-08-16-184736_276x498_scrot
2021-08-16-184726_280x290_scrot

### CODE REVIEW

**Review by taDachs — APPROVED** [review]

**Comment by taDachs** [comment]
lgtm

**Review by darius1702 — APPROVED** [review]
lgtm

**Comment by darius1702** [comment]
image

**Pull request merged**
